[project]
name = "agentlearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai[anthropic]>=1.9.3",
    "ipython>=9.10.0",
]
